--- 
- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    keyname: mohan
    region: us-east-1  
  tasks: 
    - 
      name: "remove key pair"
      ec2_key: 
          name: "{{ keypair }}"
          region: "{{ region }}"
          state: absent
  


